nav:
  - Home: index.md
  - How to Use:
    - Getting Started: HowToUse/Getting Started.md
    - Install: HowToUse/Install.md
    - Usage: HowToUse/Usage.md
    - Options: HowToUse/Options.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
  font:
    text: Fira Code
    code: Fira Code
  palette:
    primary: white
    accent: cyan
site_name: RSS Feed Creator
site_author: Tiffany White
site_description: Docs for a feed creator CLI built with Python.
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.toc:
      anchorlink: true
      permalink: true
      permalink_title: On this page